configure was out of date.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,13 +1,10 @@
 #!/bin/sh
 
-zlib=notset
-[ -f /usr/include/aspell.h -a -f /usr/include/dlfcn.h ] && spell=1
-[ -f /usr/include/zlib.h ] && zlib=1
-
 undo=1
-dopipes=1
 show_region=1
-gpm=1
+gpm=0
+zlib=0
+spell=0
 
 do_help() {
 	echo "Optional features:"
@@ -16,7 +13,7 @@ do_help() {
 	echo "  --enable-spell	Enable spell commands"
 	echo "  --enable-zlib		Enable gzip compression support"
 	echo "  --enable-sysv4	Enable if signal handlers cannot reset themselves"
-	echo "  --enable-undo		Enable UNDO"
+	echo "  --enable-undo		Enable undo"
 	echo "  --enable-show-region	Enable show region"
 	echo "  --enable-gpm		Enable gpm mouse"
 	echo "  --config-dir <dir>	Default config directory."
@@ -52,7 +49,16 @@ while [ -n "$1" ]; do
 	shift
 done
 
-[ $zlib = notset ] && echo "WARNING: Did not find zlib."
+if [ $zlib = 1 -a ! -f /usr/include/zlib.h ]; then
+    echo "Missing zlib.h"
+    exit 1
+fi
+if [ $spell = 1 ]; then
+    if [ ! -f /usr/include/aspell.h -o ! -f /usr/include/dlfcn.h ]; then
+	echo "Missing aspell.h and/or dhfcn.h"
+	exit 1
+    fi
+fi
 
 echo "/* Generated by configure `date` */" > config.h
 
@@ -72,17 +78,20 @@ set_one() {
     [ -n "$2" ] && echo "#define $1 $2" >> config.h
 }
 
-if [ $dopipes = 1 ]; then
-    set_one DOPIPES $dopipes
-else
-    set_one DOPOPEN 1
-fi
+
 set_one SPELL $spell
 set_one ZLIB $zlib
 set_one SHOW_REGION $show_region
 set_one GPM_MOUSE $gpm
-# Undo is special
-[ $undo -eq 1 ] && echo "#define UNDO 1" >> config.h
+set_one UNDO $undo
+
+if [ -n "$dopipes" ]; then
+    [ "$dopipes" -eq 1 ] && echo "#define DOPIPES" >> config.h
+else
+    echo "#ifdef __unix__" >> config.h
+    echo "#define DOPIPES" >> config.h
+    echo "#endif" >> config.h
+fi
 
 if [ "$spell" = 1 ]; then
     sed 's/^#LIBS += -ldl/LIBS += -ldl/' Makefile > Makefile.tmp
@@ -104,3 +113,15 @@ else
     sed 's/^CC = clang/#CC = clang/' Makefile > Makefile.tmp
 fi
 mv Makefile.tmp Makefile
+
+cat >> config.h <<EOF
+
+/* Don't touch these unless you really know what you are doing. */
+#define UNSIGNED_BYTES
+#define HAVE_GLOBAL_MARKS
+#define HAVE_BUFFER_MARKS
+#define HAVE_FREEMARK
+#ifdef WIN32
+#define BUILTIN_REG
+#endif
+EOF
