Allow enabling terminfo or termcap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,12 +5,18 @@ show_region=1
 gpm=0
 zlib=0
 spell=0
+terminfo=0
+termcap=0
+termcap_keys=0
 
 do_help() {
     echo "Optional features:"
     echo "  --enable-clang	Enable clang compiler"
     echo "  --enable-spell	Enable spell commands"
     echo "  --enable-zlib		Enable gzip compression support"
+    echo "  --enable-terminfo	Enable terminfo."
+    echo "  --enable-termcap	Enable termcap."
+    echo "  --enable-termcap-keys	Enable termcap for keys only."
     echo "  --enable-sysv4	Enable if signal handlers cannot reset themselves"
     echo "  --enable-undo		Enable undo"
     echo "  --enable-show-region	Enable show region"
@@ -21,6 +27,10 @@ do_help() {
     echo "To disable a feature replace --enable with --disable."
 
     exit 0
+}
+
+set_one() {
+    [ -n "$2" ] && echo "#define $1 $2" >> config.h
 }
 
 while [ -n "$1" ]; do
@@ -35,6 +45,9 @@ while [ -n "$1" ]; do
 
     case "$1" in
       *-clang) clang=$enable;;
+      *-terminfo) terminfo=$enable;;
+      *-termcap) termcap=$enable;;
+      *-termcap-keys) termcap_keys=$enable;;
       *-dopipes) dopipes=$enable;;
       *-spell) spell=$enable;;
       *-zlib) zlib=$enable;;
@@ -62,6 +75,16 @@ fi
 
 echo "/* Generated by configure `date` */" > config.h
 
+if [ $termcap = 1 -o $termcap_keys = 1 ]; then
+    [ $terminfo = 1 ] && { echo "You can't enable terminfo and termcap."; exit 1; }
+    sed -i 's/#LIBS += -ltermcap/LIBS += -ltermcap/' Makefile
+fi
+[ $terminfo = 1 ] && sed -i 's/#LIBS += -lcurses/LIBS += -lcurses/' Makefile
+
+set_one TERMINFO $terminfo
+set_one TERMCAP $termcap
+set_one TERMCAP_KEYS $termcap_keys
+
 if [ -f /usr/include/termios.h ]; then
     true
 elif [ -f /usr/include/termio.h ]; then
@@ -69,14 +92,11 @@ elif [ -f /usr/include/termio.h ]; then
 else
     echo "WARNING: No terminal setup found."
 fi
+echo >> config.h
 
 [ "$sysv4" = 1 ] && echo "#define SYSV4" >> config.h
 
 [ -n "$confdir" ] && echo "#define CONFIGDIR \"$confdir\"" >> config.h
-
-set_one() {
-    [ -n "$2" ] && echo "#define $1 $2" >> config.h
-}
 
 set_one SPELL $spell
 set_one ZLIB $zlib
