Get the help documentation working again. Split out cnames.h and var-arrays.h - makes things much easier. Save zhack.c and zhsort.c as "real" files. Update the docs.

diff --git a/docs/build b/docs/build
--- a/docs/build
+++ b/docs/build
@@ -1,3 +1,5 @@
+#!/bin/sh
+
 ZSRC=..
 CC=cc
 CFLAGS=-O
@@ -19,204 +21,23 @@ fi
 # if these don't exist, rebuild all
 [ -f help.z -a -f appab.doc ] || all=1
 
-# create zhack if necessary
-if [ ! -x zhack ]
-then
-	echo "Creating zhack"
-	cat >zhack.c <<ZHACK_END
-#include <stdio.h>
-
-main()
-{
-	int c;
-	
-	while((c = getchar()) != EOF)
-		switch(c)
-		{
-			case '_':	
-				if((c = getchar()) != '\\b')
-				{
-					ungetc(c, stdin);
-					putchar('_');
-				}
-				break;
-			case '\033':
-				if((c = getchar()) != '9') ungetc(c, stdin);
-				break;
-			default:
-				putchar(c);
-				break;
-		}
-}
-ZHACK_END
-	$CC $CFLAGS -o zhack zhack.c
-fi
-
-# this chunk creates zhsort.exe if necessary and checks the help.doc file
-[ -z "$all" ] && { echo -n "Update help.z and support files? "; read go; }
-if [ -n "$all" -o "$go" = y ]
-then
-	if [ ! -f $EXE ]
-	then
-		echo "Creating $EXE from $ZSRC"
-		cp $ZSRC/*.h .
-		echo "" >proto.h
-		echo "" >sun.h
-		echo '#define INCLUDE_VARS_STRUCT' >zhsort.c
-		echo '#include "z.h"' >>zhsort.c
-		awk /VARS_START/,/VARS_END/ $ZSRC/vars.c |
-		sed -e '/^#if/d' -e '/^#else/d' -e '/^#endif/d' >>zhsort.c
-		#add the actual code
-		cat >>zhsort.c <<END
-
-#include "cnames.h"
-
-long Locs[ NUMFUNCS ];
-
-#define COMMANDS	1
-#define VARIABLES	2
-
-main(argc, argv)
-int argc;
-char *argv[];
-{
-	FILE *fp;
-	char buff[ BUFSIZ ];
-	int err, i;
-	
-	if(argc < 3 || (*argv[1] != 'c' && *argv[1] != 'v')) {
-		puts("usage: zhsort {c | v} file");
-		exit(2);
-	}
-	if(!(fp = fopen(argv[2], "r"))) {
-		puts("unable to open file");
-		exit(2);
-	}
-
-	memset(Locs,  0xff, sizeof(long) * NUMFUNCS);
-	switch(*argv[1]) {
-	case 'c':
-		err = process(fp, COMMANDS);		
-		for( i = 0; i < NUMFUNCS; ++i )
-			if( Locs[i] == -1 ) {
-				err = TRUE;
-				fprintf( stderr, "%s: %s not found\\n", argv[2], Cnames[i].name);
-			} else if(fseek(fp, Locs[i], 0) == 0) {
-				fgets( buff, BUFSIZ, fp );
-				do
-					printf( "%s", buff );
-				while( fgets(buff, BUFSIZ, fp) && *buff != ':' );
-			} else {
-				fprintf( stderr, "Bad seek to %d\\n", Locs[i] );
-				exit( 1 );
-			}
-			break;
-			
-	case 'v':
-		err = process(fp, VARIABLES);		
-		for( i = 0; i < NUMVARS; ++i )
-			if( Locs[i] == -1 ) {
-				err = TRUE;
-				fprintf(stderr, "%s: %s not found\\n", argv[2], Vars[i].vname);
-			} else if( fseek(fp, Locs[i], 0) == 0 ) {
-				fgets( buff, BUFSIZ, fp );
-				do
-					printf( "%s", buff );
-				while( fgets(buff, BUFSIZ, fp) && *buff != ':' );
-			} else {
-				fprintf( stderr, "Bad seek to %d\\n", Locs[i] );
-				exit( 1 );
-			}
-		break;
-	}
-	fclose(fp);
-	exit( err );
-}
-
-process( fp, type )
-FILE *fp;
-int type;
-{
-	extern char *strchr();
-	char buff[ BUFSIZ ], *ptr, *eof;
-	int err = 0, i;
-	long loc = 0;
-
-	while( fgets(buff, BUFSIZ, fp) )
-	{
-		if( *buff == ':' )
-		{
-			if( ptr = strchr(buff, '\\n') ) *ptr = '\\0';
-			switch(type)
-			{
-				case COMMANDS:	
-				for( i = 0; i < NUMFUNCS; ++i )
-					if( strcmp(Cnames[i].name, &buff[1]) == 0 )
-					{	/* found it! */
-						Locs[ i ] = loc;
-						break;
-					}
-				if(i == NUMFUNCS)
-				{
-					fprintf(stderr, "unknown command: %s\n", buff);
-					err = TRUE;
-				}
-				break;
-
-				case VARIABLES:
-				for( i = 0; i < NUMVARS; ++i )
-					if( strcmp(Vars[i].vname, &buff[1]) == 0 )
-					{
-						Locs[ i ] = loc;
-						break;
-					}
-				if(i == NUMVARS)
-				{
-					fprintf(stderr, "unknown variable: %s\n", buff);
-/* SAM					err = TRUE; */
-				}
-				break;
-			}
-		}
-		loc = ftell( fp );
-	}
-	return( err );
-}
-END
-		$CC -o $EXE zhsort.c
-		[ $? -eq 0 ] || { echo "Compile failed"; exit; }
-		rm -f *.[cho] *.obj
-	fi
-
-	echo "Checking commands..."
-	$EXE c command.doc >cmd.tmp
-	[ $? -eq 0 ] || { echo "Errors: aborted"; rm -f cmd.tmp; exit; }
-	mv cmd.tmp command.doc
-	echo "Checking variables..."
-	$EXE v variable.doc >var.tmp
-	[ $? -eq 0 ] || { echo "Errors: aborted"; rm -f var.tmp; exit; }
-	mv var.tmp variable.doc
-	echo "Updating help.z"
-	# SAM no top or bottom margins, long lines
-	echo ".ll 78"	> help.head
-	echo ".m1 0"	>>help.head
-	echo ".m2 0"	>>help.head
-	echo ".m3 0"	>>help.head
-	echo ".m4 0"	>>help.head
-	echo ":ZEDIT" | nroff -me help.head command.doc variable.doc - |
-		./zhack >help.z
-
-	echo "Updating help.z.x"
-	# SAM no top or bottom margins, short lines
-	echo ".ll 40"	> help.head
-	echo ".m1 0"	>>help.head
-	echo ".m2 0"	>>help.head
-	echo ".m3 0"	>>help.head
-	echo ".m4 0"	>>help.head
-	echo ":ZEDIT" | nroff -me help.head command.doc variable.doc - |
-		./zhack >help.z.x
-	rm $EXE help.head
-fi
+echo "Checking commands..."
+$EXE c command.doc >cmd.tmp
+[ $? -eq 0 ] || { echo "Errors: aborted"; rm -f cmd.tmp; exit; }
+mv cmd.tmp command.doc
+echo "Checking variables..."
+$EXE v variable.doc >var.tmp
+[ $? -eq 0 ] || { echo "Errors: aborted"; rm -f var.tmp; exit; }
+mv var.tmp variable.doc
+echo "Updating help.z"
+# SAM no top or bottom margins, long lines
+echo ".ll 78"	> help.head
+echo ".m1 0"	>>help.head
+echo ".m2 0"	>>help.head
+echo ".m3 0"	>>help.head
+echo ".m4 0"	>>help.head
+echo ":ZEDIT" | nroff -me help.head command.doc variable.doc - |
+   ./zhack >help.z
 
 # create appendix A and B if necessary
 [ -z "$all" ] && { echo -n "Create appendicies A and B? "; read go; }
